name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t hello-world-spring-boot .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag hello-world-spring-boot samundra77/hello-world-spring-boot:latest

      - name: Push Docker image to Docker Hub
        run: docker push samundra77/hello-world-spring-boot:latest

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install hello-world ./hello-world-spring-boot --set image.repository=samundra77/hello-world-spring-boot --set image.tag=latest
